[project]
name = "conversational-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastembed>=0.7.4",
    "langchain-community>=0.4.2",
    "langchain-openai>=1.5.1",
    "langchain-qdrant>=1.1.0",
    "langchain-text-splitters",
    "langgraph>=1.2.11",
    "onnxruntime<=1.23.2",
    "python-dotenv>=1.2.3",
    "qdrant-client>=1.19.0",
]
